# Generated by Django 3.0.3 on 2020-02-24 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaftkhanSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex_name', models.CharField(max_length=200)),
                ('state_name', models.CharField(max_length=200)),
                ('city_name', models.CharField(max_length=200)),
                ('full_address', models.TextField()),
                ('is_from_kanoon_imam_reza', models.BooleanField()),
                ('head_name', models.CharField(max_length=200)),
                ('head_family_name', models.CharField(max_length=200)),
                ('head_phone_number', models.CharField(max_length=200)),
                ('teacher_name', models.CharField(max_length=200)),
                ('teacher_family_name', models.CharField(max_length=200)),
                ('teacher_education', models.CharField(max_length=200)),
                ('teacher_phone_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('family_name', models.CharField(max_length=200)),
                ('school_name', models.CharField(max_length=200)),
                ('ref_to_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.HaftkhanSignup')),
            ],
        ),
    ]
