# Generated by Django 3.0.3 on 2020-02-25 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_haftkhansignup_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='haftkhansignup',
            name='complex_phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
